name: UptainPhotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.89714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7f8286'
    - '#4a4b4e'
    - '#9da0a5'
    - '#c2c5ca'
    - '#0d0d0d'
  brandStrength: 0
  lightness: 0.5183764593675733
  saturation: 0.7673549931496382
  rhythmicContrast: 0.888488732278347
purpose: []
